import type { GrammarPart } from "@/lib/types/content";

const part1: GrammarPart = {
  partNumber: 1,
  kind: "sentence-completion",
  items: [
    {
      id: "g1-q1",
      prompt: "___ the traffic, we still managed to arrive on time.",
      choices: ["Because of", "Despite", "Although", "Unless"],
      correctIndex: 1,
      explanation: "'Despite' is followed directly by a noun phrase; 'although' would require a full clause instead.",
    },
    {
      id: "g1-q2",
      prompt: "By next June, she ___ at the company for ten years.",
      choices: ["will work", "has worked", "was working", "will have been working"],
      correctIndex: 3,
      explanation: "Future perfect continuous emphasizes the duration of an action continuing up to a specified future point.",
    },
    {
      id: "g1-q3",
      prompt: "The manager asked ___ the deadline could be extended.",
      choices: ["whether", "that", "when did", "if not"],
      correctIndex: 0,
      explanation: "Reported yes/no questions are introduced with 'whether' or 'if', followed by statement word order.",
    },
    {
      id: "g1-q4",
      prompt: "No sooner ___ the presentation than the fire alarm went off.",
      choices: ["he had finished", "did he finish", "had he finished", "he finished"],
      correctIndex: 2,
      explanation: "'No sooner...than' triggers inversion with the past perfect: 'no sooner had he finished.'",
    },
    {
      id: "g1-q5",
      prompt: "The proposal, ___ merits are widely recognized, still faces budget obstacles.",
      choices: ["that", "whose", "which", "who"],
      correctIndex: 1,
      explanation: "'Whose' shows possession, referring back to 'the proposal's merits.'",
    },
    {
      id: "g1-q6",
      prompt: "I wish I ___ more carefully before signing the contract.",
      choices: ["read", "would read", "have read", "had read"],
      correctIndex: 3,
      explanation: "'Wish' + past perfect expresses regret about something that did or didn't happen in the past.",
    },
    {
      id: "g1-q7",
      prompt: "The results were ___ surprising that the team repeated the experiment.",
      choices: ["so", "such", "too", "very"],
      correctIndex: 0,
      explanation: "'So + adjective + that' introduces a result clause; 'such' would require 'such + noun.'",
    },
    {
      id: "g1-q8",
      prompt: "Were the funding ___ available, the research would proceed immediately.",
      choices: ["is", "being", "to be", "been"],
      correctIndex: 2,
      explanation: "This is an inverted conditional: 'were the funding to be available' = 'if the funding were to be available.'",
    },
    {
      id: "g1-q9",
      prompt: "The committee is expected to announce its decision ___ the end of the week.",
      choices: ["until", "by", "since", "during"],
      correctIndex: 1,
      explanation: "'By' marks a deadline (an action completed at or before a point in time); 'until' marks duration.",
    },
    {
      id: "g1-q10",
      prompt: "She would rather her colleagues ___ the announcement before the meeting.",
      choices: ["don't make", "won't make", "don't have made", "hadn't made"],
      correctIndex: 3,
      explanation: "'Would rather' + subject + past perfect expresses a preference about something that already happened.",
    },
    {
      id: "g1-q11",
      prompt: "Rarely ___ such a compelling argument presented so concisely.",
      choices: ["have I heard", "I have heard", "I heard", "did I heard"],
      correctIndex: 0,
      explanation: "The negative adverbial 'rarely' at the start of a sentence triggers subject-auxiliary inversion.",
    },
    {
      id: "g1-q12",
      prompt: "The engineers must ensure that the bridge ___ strict safety codes.",
      choices: ["meets", "meet", "is meeting", "met"],
      correctIndex: 2,
      explanation: "The mandative subjunctive after 'ensure that' uses the base form of the verb regardless of subject.",
    },
    {
      id: "g1-q13",
      prompt: "It was not until she moved abroad ___ she appreciated her hometown.",
      choices: ["so", "that", "when", "then"],
      correctIndex: 1,
      explanation: "This is a cleft structure: 'It was not until X that Y' emphasizes the timing of the realization.",
    },
  ],
};

const part2: GrammarPart = {
  partNumber: 2,
  kind: "error-identification",
  items: [
    {
      id: "g2-q1",
      prompt: "Everyone in the office are required to submit their timesheets by Friday afternoon without exception.",
      choices: [
        "Everyone in the office are required",
        "to submit their timesheets",
        "by Friday afternoon",
        "without exception.",
      ],
      correctIndex: 0,
      explanation: "'Everyone' is grammatically singular, so the verb should be 'is required'.",
    },
    {
      id: "g2-q2",
      prompt: "The professor, together with her graduate students, are preparing for the conference next month.",
      choices: [
        "The professor,",
        "together with her graduate students,",
        "are preparing",
        "for the conference next month.",
      ],
      correctIndex: 2,
      explanation: "The subject is 'the professor' (singular); a phrase introduced by 'together with' doesn't change agreement, so it should be 'is preparing'.",
    },
    {
      id: "g2-q3",
      prompt: "Since the merger, the company has hired considerably fewer employees, but customer complaints have actually increased more quicker than expected.",
      choices: [
        "Since the merger,",
        "the company has hired considerably fewer employees,",
        "but customer complaints have actually increased",
        "more quicker than expected.",
      ],
      correctIndex: 3,
      explanation: "'More quicker' is a double comparative; it should simply be 'quicker' or 'more quickly', not both together.",
    },
    {
      id: "g2-q4",
      prompt: "The average tourist spend more money on food than on souvenirs during a typical trip.",
      choices: [
        "The average tourist",
        "spend more money",
        "on food than on souvenirs",
        "during a typical trip.",
      ],
      correctIndex: 1,
      explanation: "'The average tourist' is singular, so the verb should be 'spends'.",
    },
    {
      id: "g2-q5",
      prompt: "Neither of the applicants have submitted their references yet, which is delaying the hiring process.",
      choices: [
        "Neither of the applicants have submitted",
        "their references yet,",
        "which is delaying",
        "the hiring process.",
      ],
      correctIndex: 0,
      explanation: "'Neither' is grammatically singular, so it should be 'has submitted'.",
    },
    {
      id: "g2-q6",
      prompt: "The board praised the report for being written clearly, but felt the conclusion needed to more directly addresses the risks.",
      choices: [
        "The board praised the report",
        "for being written clearly,",
        "but felt the conclusion needed to more directly addresses",
        "the risks.",
      ],
      correctIndex: 2,
      explanation: "After 'to', the base form is required: it should be 'to more directly address the risks', not 'addresses'.",
    },
    {
      id: "g2-q7",
      prompt: "After reviewing dozens of applications, the hiring committee finally chosen the two strongest candidates.",
      choices: [
        "After reviewing dozens of applications,",
        "the hiring committee",
        "finally",
        "chosen the two strongest candidates.",
      ],
      correctIndex: 3,
      explanation: "Without an auxiliary verb, the simple past 'chose' is needed, not the past participle 'chosen'.",
    },
    {
      id: "g2-q8",
      prompt: "Most of the equipment in the lab need to be replaced before the semester starts.",
      choices: [
        "Most of the equipment in the lab",
        "need to be replaced",
        "before the semester",
        "starts.",
      ],
      correctIndex: 1,
      explanation: "'Equipment' is an uncountable noun treated as singular, so it should be 'needs to be replaced'.",
    },
    {
      id: "g2-q9",
      prompt: "Statistics show that the economy are recovering faster than analysts predicted.",
      choices: [
        "Statistics show that the economy are recovering",
        "faster than",
        "analysts",
        "predicted.",
      ],
      correctIndex: 0,
      explanation: "'The economy' is singular, so it should be 'the economy is recovering'.",
    },
    {
      id: "g2-q10",
      prompt: "The workshop taught participants how to use the software more efficient and avoid common mistakes.",
      choices: [
        "The workshop taught participants",
        "how to use the software",
        "more efficient and",
        "avoid common mistakes.",
      ],
      correctIndex: 2,
      explanation: "An adverb is needed to modify 'use', so it should be 'more efficiently', not the adjective 'efficient'.",
    },
    {
      id: "g2-q11",
      prompt: "The negotiations dragged on for months before both sides finally agreed on the terms who were acceptable to everyone.",
      choices: [
        "The negotiations dragged on for months",
        "before both sides finally agreed",
        "on the terms",
        "who were acceptable to everyone.",
      ],
      correctIndex: 3,
      explanation: "'Terms' is a thing, not a person, so the relative pronoun should be 'that' or 'which', not 'who'.",
    },
    {
      id: "g2-q12",
      prompt: "The documentary explores how climate change affecting coastal communities around the world.",
      choices: [
        "The documentary explores",
        "how climate change affecting",
        "coastal communities",
        "around the world.",
      ],
      correctIndex: 1,
      explanation: "The noun clause needs a finite verb: it should be 'how climate change affects', not the participle 'affecting'.",
    },
  ],
};

export const grammarContent = {
  totalTimeSeconds: 10 * 60,
  parts: [part1, part2] as [GrammarPart, GrammarPart],
};
