import type { GrammarPart } from "@/lib/types/content";

const part1: GrammarPart = {
  partNumber: 1,
  kind: "sentence-completion",
  items: [
    {
      id: "g1-q1",
      prompt: "By the time the meeting starts tomorrow, the committee ___ its final decision.",
      choices: ["will make", "has made", "will have made", "would make"],
      correctIndex: 2,
      explanation: "Future perfect (will have + past participle) describes an action completed before a specified future time.",
    },
    {
      id: "g1-q2",
      prompt: "She insisted that he ___ the report before submitting it.",
      choices: ["revise", "revises", "revised", "revising"],
      correctIndex: 0,
      explanation: "The mandative subjunctive after verbs like 'insist' uses the base form of the verb regardless of subject.",
    },
    {
      id: "g1-q3",
      prompt: "Neither the manager nor the employees ___ satisfied with the new policy.",
      choices: ["was", "is", "has been", "were"],
      correctIndex: 3,
      explanation: "With 'neither...nor', the verb agrees with the noun closest to it — here, 'employees' (plural).",
    },
    {
      id: "g1-q4",
      prompt: "The museum, ___ was built in the 1800s, attracts thousands of visitors annually.",
      choices: ["that", "which", "who", "whose"],
      correctIndex: 1,
      explanation: "Non-defining relative clauses referring to things use 'which', not 'that'.",
    },
    {
      id: "g1-q5",
      prompt: "If the funding had been approved earlier, the project ___ on schedule.",
      choices: ["would finish", "will finish", "would have finished", "finished"],
      correctIndex: 2,
      explanation: "Third conditional: if + past perfect, would have + past participle, for a hypothetical past result.",
    },
    {
      id: "g1-q6",
      prompt: "It's essential that every applicant ___ the form in black ink.",
      choices: ["complete", "completes", "completed", "will complete"],
      correctIndex: 0,
      explanation: "Adjectives like 'essential that' trigger the same mandative subjunctive as 'insist' or 'recommend'.",
    },
    {
      id: "g1-q7",
      prompt: "The company is considering ___ its operations to Southeast Asia next year.",
      choices: ["expand", "to expand", "expanded", "expanding"],
      correctIndex: 3,
      explanation: "The verb 'consider' is followed by a gerund, not an infinitive.",
    },
    {
      id: "g1-q8",
      prompt: "Hardly ___ the announcement been made when the stock prices began to fall.",
      choices: ["was", "had", "has", "did"],
      correctIndex: 1,
      explanation: "'Hardly...when' requires inversion with the past perfect: Hardly had + subject + past participle.",
    },
    {
      id: "g1-q9",
      prompt: "The evidence suggests that climate change is occurring at a much faster rate than ___ previously.",
      choices: ["believed", "believes", "was believed", "has believing"],
      correctIndex: 2,
      explanation: "An impersonal passive construction is needed here: 'than was believed' (previously), matching the past reference.",
    },
    {
      id: "g1-q10",
      prompt: "You'd better ___ your presentation before the client arrives.",
      choices: ["finish", "finishing", "to finish", "finished"],
      correctIndex: 0,
      explanation: "'Had better' is always followed by the bare infinitive (without 'to').",
    },
    {
      id: "g1-q11",
      prompt: "Despite ___ warned about the risks, investors continued to pour money into the venture.",
      choices: ["being", "have been", "to be", "having been"],
      correctIndex: 3,
      explanation: "'Despite' is followed by a gerund; since the warning happened earlier, the perfect passive gerund 'having been warned' is required.",
    },
    {
      id: "g1-q12",
      prompt: "Not only ___ the deadline missed, but the budget was also exceeded.",
      choices: ["did", "was", "has", "is"],
      correctIndex: 1,
      explanation: "'Not only' at the start of a clause triggers inversion; the passive 'was...missed' fits the context.",
    },
    {
      id: "g1-q13",
      prompt: "The professor recommended that the thesis ___ before the final defense.",
      choices: ["is revised", "was revised", "be revised", "will be revised"],
      correctIndex: 2,
      explanation: "The mandative subjunctive can be passive: recommend that + subject + be + past participle.",
    },
  ],
};

const part2: GrammarPart = {
  partNumber: 2,
  kind: "error-identification",
  items: [
    {
      id: "g2-q1",
      prompt: "Despite of the heavy rain, the marathon organizers decided to proceed with the race as scheduled.",
      choices: [
        "the marathon organizers decided",
        "to proceed with the race",
        "as scheduled",
        "Despite of the heavy rain,",
      ],
      correctIndex: 3,
      explanation: "'Despite' is never followed by 'of' — it should be simply 'Despite the heavy rain' or 'In spite of the heavy rain'.",
    },
    {
      id: "g2-q2",
      prompt: "Each of the candidates were asked to submit a writing sample before the interview process began.",
      choices: [
        "Each of the candidates",
        "to submit a writing sample",
        "were asked",
        "before the interview process began",
      ],
      correctIndex: 2,
      explanation: "'Each' is grammatically singular, so the verb should be 'was asked'.",
    },
    {
      id: "g2-q3",
      prompt: "The committee members, along with the director, has reviewed the proposal thoroughly.",
      choices: [
        "The committee members,",
        "has reviewed",
        "along with the director,",
        "the proposal thoroughly",
      ],
      correctIndex: 1,
      explanation: "The subject is 'members' (plural); a phrase introduced by 'along with' doesn't change subject-verb agreement, so it should be 'have reviewed'.",
    },
    {
      id: "g2-q4",
      prompt: "By the time she arrives, we will have already finish setting up the conference room.",
      choices: [
        "we will have already finish",
        "By the time she arrives,",
        "setting up",
        "the conference room",
      ],
      correctIndex: 0,
      explanation: "The future perfect requires a past participle: 'will have already finished'.",
    },
    {
      id: "g2-q5",
      prompt: "The report contains less errors than the previous draft, which surprised the editorial team.",
      choices: [
        "than the previous draft,",
        "which surprised",
        "the editorial team",
        "The report contains less errors",
      ],
      correctIndex: 3,
      explanation: "'Errors' is a countable noun, so 'fewer errors' is required instead of 'less errors'.",
    },
    {
      id: "g2-q6",
      prompt: "If I would have known about the schedule change, I would have rearranged my appointments.",
      choices: [
        "about the schedule change,",
        "I would have rearranged",
        "If I would have known",
        "my appointments",
      ],
      correctIndex: 2,
      explanation: "Third conditional 'if' clauses use the past perfect, not 'would have': it should be 'If I had known'.",
    },
    {
      id: "g2-q7",
      prompt: "The number of students who are choosing to study abroad have increased significantly this decade.",
      choices: [
        "The number of students",
        "have increased",
        "who are choosing to study abroad",
        "significantly this decade",
      ],
      correctIndex: 1,
      explanation: "'The number of' takes a singular verb ('has increased'); it is 'a number of' that takes a plural verb.",
    },
    {
      id: "g2-q8",
      prompt: "She is one of the few managers who is willing to listen to employee feedback during quarterly reviews.",
      choices: [
        "who is willing to listen",
        "She is one of the few managers",
        "to employee feedback",
        "during quarterly reviews",
      ],
      correctIndex: 0,
      explanation: "'Who' refers back to 'managers' (plural), so the verb should be 'who are willing'.",
    },
    {
      id: "g2-q9",
      prompt: "The engineer explained us the reason for the delay in a very clear and concise manner.",
      choices: [
        "the reason for the delay",
        "in a very clear",
        "and concise manner",
        "The engineer explained us",
      ],
      correctIndex: 3,
      explanation: "'Explain' is not ditransitive; it requires 'to': 'explained to us the reason...' or 'explained the reason to us'.",
    },
    {
      id: "g2-q10",
      prompt: "Having finished the experiment, the results were analyzed carefully by the research team.",
      choices: [
        "Having finished the experiment,",
        "carefully by",
        "the results were analyzed",
        "the research team",
      ],
      correctIndex: 2,
      explanation: "Dangling modifier: it was the research team, not 'the results', that finished the experiment. It should read '...the research team analyzed the results carefully.'",
    },
    {
      id: "g2-q11",
      prompt: "The company's profits has grown steadily since it expanded into new markets last year.",
      choices: [
        "The company's profits",
        "has grown steadily",
        "since it expanded",
        "into new markets last year",
      ],
      correctIndex: 1,
      explanation: "'Profits' is plural, so the verb should be 'have grown'.",
    },
    {
      id: "g2-q12",
      prompt: "Scarcely had the plane landed than the passengers began to applaud the pilot's skill.",
      choices: [
        "than the passengers began",
        "Scarcely had the plane landed",
        "to applaud",
        "the pilot's skill",
      ],
      correctIndex: 0,
      explanation: "'Scarcely...when' is the correct pairing (not 'scarcely...than'), so it should be 'when the passengers began'.",
    },
  ],
};

export const grammarContent = {
  totalTimeSeconds: 10 * 60,
  parts: [part1, part2] as [GrammarPart, GrammarPart],
};
